<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            ["name" => "Estela Vieira Santana Monteiro", "email" => "stelavds@yahoo.com.com"],
            ["name" => "Luciana Vieira Martins", "email" => "luvmartins@yahoo.com.br"],
            ["name" => "Beatriz Amorim de Medeiros", "email" => "beamedeiros28@gmail.com"],
            ["name" => "Mariana Prearo", "email" => "marianaprearo@yahoo.com.br"],
            ["name" => "Mayara Machado de Castro Lagares", "email" => "mayara.mcastro@hotmail.com"],
            ["name" => "Paglia Pedrosa Barboza", "email" => "paglia.barboza@gmail.com"],
            ["name" => "Sofia de Araujo Mendes", "email" => "sofiaamendes@icloud.com"],
            ["name" => "Bruna Monteiro Ramos", "email" => "bumonteiro_7@hotmail.com"],
            ["name" => "Rogéria Reis ", "email" => "rogeriareis@yahoo.com.br"],
            ["name" => "Raquel Bicalho Portugal Pimenta", "email" => "quelportugal@hotmail.com"],
            ["name" => "Sandra Milena Cardona Urrea", "email" => "sanmileca@hotmail.es"],
            ["name" => "Mayra Leticia Vieira Duarte Nunes", "email" => "mayra@rnunes.cnt.br"],
            ["name" => "Marina Reis Claudio", "email" => "marinanitas@yahoo.com.br"],
            ["name" => "Thissiane Cristina Coelho Ribeiro", "email" => "thissi13@hotmail.com"],
            ["name" => "Renata de Magalhães Chernicharo Franco", "email" => "rchernicharo@gmail.com"],
            ["name" => "Juliana Silveira Teixeira ", "email" => "julianateixeira@outlook.com"],
            ["name" => "Emanuelle de Fátima Ferreira Oliveira", "email" => "emanuelleortodontia@gmail.com"],
            ["name" => "Taiana Stofella de Souza", "email" => "taianastofella@hotmail.com"],
            ["name" => "Daniele Cristiane Teixeira", "email" => "danipequena43@gmail.com"],
            ["name" => "Tatiane Caroline Afonso", "email" => "tatianettg@gmail.com"],
            ["name" => "Mariana Fernandes Martins de Castro", "email" => "fisio.marianamartins@gmail.com"],
            ["name" => "Fabiana Batista Corrêa", "email" => "fabiana.bcor@gmail.com"],
            ["name" => "Marcela Borges Lima", "email" => "marcelaborgeslima@yahoo.com.br"],
            ["name" => "Daniela Valadares Camargos", "email" => "danycamargos@yahoo.com.br"],
            ["name" => "Carolina de Oliveira Souza", "email" => "carolinaosouza@yahoo.com.br"],
            ["name" => "Gabrielle Eimi Mitsunari", "email" => "gabrielle_eimi@hotmail.com"],
            ["name" => "Patrícia Miranda de Andrade", "email" => "mpatyandrade8@gmail.com"],
            ["name" => "Daniela de Campos Barreto Vieira", "email" => "danielacbarreto@gmail.com"],
            ["name" => "Sandra Cristina Silveira de Oliveira", "email" => "sandracrisioly@gmail.com"],
            ["name" => "Débora Fernandes Ferreira Baeta Neves", "email" => "dra.debora.baeta@gmail.com"],
            ["name" => "Greice Camparo Braido", "email" => "greicecbraido@gmail.com"],
            ["name" => "Carla Jukel Ferreira", "email" => "carlajeckel@gmail.com"],
            ["name" => "Paula Cheik Freire Cabral ", "email" => "paulacheik@gmail.com"],
            ["name" => "Gabriela Torres Dias", "email" => "gabitorres_enf@yahoo.com.br"],
            ["name" => "Najlla Lopes de Oliveira Burle", "email" => "najllaburle@gmail.com"],
            ["name" => "Amanda Dalsecco Ribeiro", "email" => "amandadalsecco@hotmail.com"],
            ["name" => "Cynthia Maria Mello", "email" => "cynthiamlmello@gmail.com"],
            ["name" => "Joana Paula N. Calaça", "email" => "joanacalaca@gmail.com"],
            ["name" => "Amanda Letícia Amaral Madeira e Silva", "email" => "amanda.madeira@gmail.com"],
            ["name" => "Debora Menezes de Figueiredo", "email" => "figueiredod2013@gmail.com"],
            ["name" => "Sheila Spagnol de Oliveira Salvaterra", "email" => "sheilaspagnol@hotmail.com"],
            ["name" => "Deliane Maria Ribeiro", "email" => "deliane.ribeiro@gmail.com"],
            ["name" => "Ana Paula Ming Branco Amaral", "email" => "anapaulaming03@gmail.com"],
            ["name" => "Raiane Ronize Noronha da Silva", "email" => "raianeronize@icloud.com"],
            ["name" => "Rafaela Ferreira Leite", "email" => "rafaela.leite@outlook.com.br"],
            ["name" => "Raíssa Lobenwein Machado", "email" => "raissa.lmmachado@gmail.com"],
            ["name" => "Tâmara Pessoa Oliveira Tagliatti", "email" => "tamarajf@hotmail.com"],
            ["name" => "Juliana Silva de Lana", "email" => "juslana@hotmail.com"],
            ["name" => "Ingrid Matos de Araújo Góes", "email" => "ingridgoes1@gmail.com"],
            ["name" => "Aline Cristina Pimenta Siqueira", "email" => "alinecps87@gmail.com"],
            ["name" => "Priscila Moraes Figueiredo", "email" => "priscilamoraesfigueiredo@gmail.com"],
            ["name" => "Luiza Veltem Chamone", "email" => "luveltem@hotmail.com"],
            ["name" => "Stephanie Raysa Iltis Raposo", "email" => "stephanieiltis@yahoo.com.br"],
            ["name" => "Pollyanna A. Soares Barcelos", "email" => "pollyannabarcellos4@gmail.com"],
            ["name" => "Veridianne Soares Nazareth Magacho", "email" => "Veridianne.soares@gmail.com"],
            ["name" => "Mariana Silva Borba", "email" => "marianasp.adm@gmail.com"],
            ["name" => "Lorena Machado Meneses", "email" => "lorenamachado.adv@gmail.com"],
            ["name" => "Gabriella Barbosa Manzali", "email" => "beneficios@manzalliseguros.com.br"],
            ["name" => "Thais Nara Faria Duarte", "email" => "thaisfaria@live.com"],
            ["name" => "Lehiza Santos Souza", "email" => "lehizasantos@hotmail.com"],
            ["name" => "Jerusa Ferreira Vale Martinez", "email" => "jerusapedagogia@gmail.com"],
            ["name" => "Franciele Francisca Corrêa Schmidt", "email" => "franciele.fcorrea@hotmail.com"],
            ["name" => "Tathiana Rohlfs Lorenzato Silva", "email" => "t.rohlfs@hotmail.com"],
            ["name" => "Manuela Vieira Mansur", "email" => "dramanuelamansur87@gmail.com"],
            ["name" => "Renata Silva Campos", "email" => "renatasre@gmail.com"],
            ["name" => "Taise Assis Santana", "email" => "taise.santana81@gmail.com"],
            ["name" => "Larah Malonne Gomes Pelegrini", "email" => "larahmalonne@gmail.com"],
            ["name" => "Taciana Riccio Franklin", "email" => "taciriccio@hotmail.com"],
            ["name" => "Darquia Gonçalves Barroso de Carvalho", "email" => "darquialc@gmail.com"],
            ["name" => "Sula Mila Melo Frizzone", "email" => "sulamilasil@hotmail.com"],
            ["name" => "Priscyla Angely Alves Aguiar", "email" => "priangely@gmail.com"],
            ["name" => "Deborah de Almeida Magalhães", "email" => "dehm@ymail.com"],
            ["name" => "Rafaella Flores Veloso Chuquer", "email" => "rafavchuquer@gmail.com"],
            ["name" => "Yasmim Araujo de Paula", "email" => "yasmimaraujodepaula@gmail.com"],
            ["name" => "Luiza Lima Ferraz", "email" => "luizaferraz.fisio@outlook.com"],
            ["name" => "Maria Claudia Moreira", "email" => "kakamoreira15@yahoo.com.br"],
            ["name" => "Ana Paula Botelho Pedrosa", "email" => "anabotelhopedrosa@gmail.com"],
            ["name" => "Paula Ciccone Michel Oliveira Garcia", "email" => "paulacmichel@gmail.com"],
            ["name" => "Bárbara Lizandra Nascimento", "email" => "barbaralizandra@gmail.com"],
            ["name" => "Camila Breder Gondim", "email" => "camilabreder91@gmail.com"],
            ["name" => "Fernanda Helena Amaral de Oliveira", "email" => "fe107107@gmail.com"],
            ["name" => "Ana Carolina Cosse Andrade", "email" => "carolcosse@yahoo.com.br"],
            ["name" => "Gabriela Resende da Silva", "email" => "gaby-rds@hotmail.com"],
            ["name" => "Camila de Souza Menezes", "email" => "milasmenezes@yahoo.com.br"],
            ["name" => "Danielle Maciel Velloso Leão Vidigal", "email" => "daniellevidigal@hotmail.com"],
            ["name" => "Priscilla Lazzarini Pereira", "email" => "priscilla.lazzarini@gmail.com"],
            ["name" => "Rafaelle Modesto Alves", "email" => "rafa.modesto03@gmail.com"],
            ["name" => "Mariana Peixoto Calijorne", "email" => "mari.peixotoc@hotmail.com"],
            ["name" => "Marina Parreira Guimarães", "email" => "marimap@hotmail.com"],
            ["name" => "Paula Correia Neves", "email" => "paulacorreianeves@hotmail.com"],
            ["name" => "Isabela Nascimento Calaça", "email" => "isabela.calaca@gmail.com"],
            ["name" => "Aline Dutra de Rezende Freitas", "email" => "dutra.aline84@hotmail.com"],
            ["name" => "Tifany da Silva Sato Roca", "email" => "tifanyroca123@gmail.com"],
            ["name" => "Carolinne Squarcio Soares Oliveira dos Passos", "email" => "carolss91@hotmail.com"],
            ["name" => "Roberta Andrade Cruz", "email" => "robertaa_cruz@yahoo.com.br"],
            ["name" => "Nayana Arruti Santos", "email" => "nayaraarruti@gmail.com"],
            ["name" => "Carolina Abras Morato Toscano", "email" => "carolamorato@hotmail.com"],
            ["name" => "Thaysa Kasis de Faria Alvim Orlandi", "email" => "thaysaalvim@yahoo.com.br"],
            ["name" => "Laodiceia Duarte de Oliveira", "email" => "laudiceiaduarte@hotmail.com"],
            ["name" => "Fernanda de Oliveira Coral", "email" => "nandacoral20@hotmail.com"],
            ["name" => "Katty Sierra Barrios", "email" => "kasb1094@hotmail.com"],
            ["name" => "Camila Salomão Sales e Silva", "email" => "camilasalomao10@hotmail.com"],
            ["name" => "Sara de Souza Oliveira", "email" => "sara@endolifemed.com.br"],
            ["name" => "Paloma Almeida Diniz", "email" => "palomadinizfisio@gmail.com"],
            ["name" => "Nadja Sherrine Soares Godoy Paiva Oliveira", "email" => "nadjasherrine@yahoo.com.br"],
            ["name" => "Demille Cristine da Silva Taciano Siqueira", "email" => "demillecristine@gmail.com"],
            ["name" => "Angelica Martins de Oliveira", "email" => "angelmpersonal@gmail.com"],
            ["name" => "Daniela Penido Benhame Resende", "email" => "daniela.penido@hotmail.com"],
            ["name" => "Mariana Ferreira Resende", "email" => "marianaresende.eng@gmail.com"],
            ["name" => "Carolina Fantini de Souza Carneiro", "email" => "carolinafantini@hotmail.com"],
            ["name" => "Nayara Martins Ferreira", "email" => "nayaramartinsf.m@gmail.com"],
            ["name" => "Juliana Silva Magno Baptista", "email" => "julianamagno1@hotmail.com"],
            ["name" => "Luiza Signorelli de Andrade", "email" => "luizasignorelli.a@gmail.com"],
            ["name" => "Gabriella Maia da Silva", "email" => "gabriellamaia0902@gmail.com"],
            ["name" => "Elaine Cristina de Carvalho", "email" => "elaine.carvalho78@yahoo.com.br"],
            ["name" => "Elluza Rocha Ribeiro Fagundes", "email" => "elluzarribeiro@gmail.com"],
            ["name" => "Nathalia Nahja Pessoa Nogueira Gomes", "email" => "nnahja@yahoo.com.br"],
            ["name" => "Camila Lima Dias", "email" => "camilaldias@hotmail.com"],
            ["name" => "Aline Cassia de Andrade", "email" => "alinesayao@bol.com.br / alinesayao@sescmg.com.br"],
            ["name" => "Flavia de Araújo Pereira", "email" => "flavia.apereira@hotmail.com"],
            ["name" => "Kenia Janete Guerra", "email" => "geokenia@hotmail.com"],
            ["name" => "Juliana Borges Mendes", "email" => "juborgesmendes@gmail.com"],
            ["name" => "Nathalia Christina Passos ", "email" => "nathypassos@hotmail.com"],
            ["name" => "Sabrina Rochana Almeida de Paula Pereira", "email" => "rochana1@hotmail.com"],
            ["name" => "Leandra Ribeiro Ramos Magalhães", "email" => "lerrm.tap@gmail.com"],
            ["name" => "Fernanda Morcatti Coura", "email" => "fernandamorcatti@yahoo.com.br"],
            ["name" => "Daniel Monteiro de Souza", "email" => "danielmsejc@hotmail.com"],
            ["name" => "Luiz Henrique Viana Duarte", "email" => "luizhduarte2010@hotmail.com"],
            ["name" => "Frederico Correa Nogueira", "email" => "fcnogueira29@gmail.com"],
            ["name" => "Gilson Angelo Zanetti Gonçalves", "email" => "gilsonzanetti@yahoo.com.br"],
            ["name" => "Bruno Lagares de Andrade ", "email" => "brumaq@yahoo.com"],
            ["name" => "Hugo Antonio P. Teixeira", "email" => "hugo@prismaindustrial.com.br"],
            ["name" => "Marcelo San Severino Batista de Castro", "email" => "marcelosancastro@yahoo.com.br"],
            ["name" => "Gabriel de Vargas Mourao", "email" => "gabriel.mourao@yahoo.com.br"],
            ["name" => "Rogério Trindade Piza", "email" => "rogeriotpiza@hotmail.com"],
            ["name" => "Márcio Gonçalves Pimenta Júnior", "email" => "juniorex@gmail.com"],
            ["name" => "Miguel Angel Garcia Garcia", "email" => "miguel2100@hotmail.com"],
            ["name" => "Rodrigo Silva Moreira Nunes", "email" => "rodrigo@rnunes.cnt.br"],
            ["name" => "Vinicius de Oliveira Cunha", "email" => "viniciusocunha@yahoo.com.br"],
            ["name" => "Brenno Moreira Franco", "email" => "brennomfranco@gmail.com"],
            ["name" => "Ianno Santos Soares", "email" => "iannosoares@hotmail.com"],
            ["name" => "Sebastião Guilherme de Oliveira Neto", "email" => "drsebastiaoneto@gmail.com"],
            ["name" => "Rodrigo Lana de Almeida ", "email" => "rodrigo.lana@vale.com"],
            ["name" => "Fernando Ferreira de Souza", "email" => "fernandofds.adv@gmail.com"],
            ["name" => "Italo Koji Koyama", "email" => "italo.koyama@gmail.com"],
            ["name" => "Ademilson Miranda da Silva", "email" => "ademilsonmiranda@hotmail.com"],
            ["name" => "Fernando Cavalcanti de Castro", "email" => "fernandocdecastro@gmail.com"],
            ["name" => "Rodolfo Sapi Rossignoli", "email" => "rodolfosapi@gmail.com"],
            ["name" => "Bernardo Chalup Barone", "email" => "bernardochalup@gmail.com"],
            ["name" => "Joao Sergio Agostinho Bonzi", "email" => "js.bonzi@yahoo.com.br"],
            ["name" => "Fabrício André Figueiredo", "email" => "fabricio_a_figueiredo@yahoo.com.br"],
            ["name" => "Leandro Hideki Ishi", "email" => "ishi.leandro@gmail.com"],
            ["name" => "Ícaro Ferraz Saldanha", "email" => "icaroferrazsaldanha1997@gmail.com"],
            ["name" => "Fabiano Silva Vieira", "email" => "fabiano.vieira@ale.com.br"],
            ["name" => "Marcus Vinicius de Lima", "email" => "marcusvilly@outlook.com"],
            ["name" => "Nilson Luis da Cruz Pereira", "email" => "nilsonlcp@ig.com.br"],
            ["name" => "Wender Damasceno Visintin", "email" => "wendervisi2017@gmail.com"],
            ["name" => "Nuno Lima Roquete", "email" => "nunoroquete@gmail.com"],
            ["name" => "Pedro Henrique Pereira de Sousa", "email" => "pedro.sousa@allcance.net.br"],
            ["name" => "Ricardo Queiroz Rodrigues", "email" => "ricardoqrzo@hotmail.com"],
            ["name" => "Guilherme Pessoa Guimarães Santos", "email" => "guipessoa10@hotmail.com"],
            ["name" => "Bruno Gomes Guimaraes", "email" => "Bruno.Guimaraes1987@gmail.com"],
            ["name" => "Daniel Dias Oliveira", "email" => "danieldiasoliveira@gmail.com"],
            ["name" => "Michel Angelo Martins Silva", "email" => "michel.martins80@gmail.com"],
            ["name" => "Paulo Vinicius Neves Ribas", "email" => "figueiredod@globo.com"],
            ["name" => "Clemilson Fernandes Salvaterra", "email" => "clemilson.salvaterra@gmail.com"],
            ["name" => "Fabio Luiz Firmino Leles", "email" => "fabioleles@yahoo.com.br"],
            ["name" => "Jefferson Nascimento Amaral", "email" => "jeffersonamaral@outlook.com"],
            ["name" => "Fernando Vida e Silva", "email" => "fernandovidaadvogado@gmail.com"],
            ["name" => "Filipe Marques S. Pereira", "email" => "filipede@hotmail.com"],
            ["name" => "Leonardo de Assis Santos", "email" => "assisleonardo@gmail.com"],
            ["name" => "Rafael Tagliatti Herédia", "email" => "rafaeltagliatti@hotmail.com"],
            ["name" => "Rodrigo Souza Batista", "email" => "rodrigoautomacao@gmail.com"],
            ["name" => "Gabriel Paiva Campos", "email" => "tinpaiva@hotmail.com"],
            ["name" => "Higor Gustavo Romualdo Rola", "email" => "higorromualdo51@gmail.com"],
            ["name" => "Luiz dos Reis Borges Junior", "email" => "luizreisborges@gmail.com"],
            ["name" => "Wagner Jeronimo Junior", "email" => "wagner.jeronimo@waybarcon.com"],
            ["name" => "Ulisses Alves de Oliveira", "email" => "ulissesalvesoliveira@hotmail.com"],
            ["name" => "Luiz Fernando Martins Dornellas", "email" => "luizmartinsdornellas@gmail.com"],
            ["name" => "Bernard Pereira Magacho", "email" => "bpmagacho@gmail.com"],
            ["name" => "Marcus Vinicius Barros Borba", "email" => "drmarcusborba.adm@gmail.com"],
            ["name" => "Bruno Meneses Alves Faria", "email" => "brunomeneses@msn.com"],
            ["name" => "Marcell Ferreira Pinho", "email" => "MARCELLPINHO@YAHOO.COM.BR"],
            ["name" => "Thalys Henrique Duarte Velloso", "email" => "thalysduarte@hotmail.com"],
            ["name" => "Alexandre Paulo da Silva Castro", "email" => "alexandreps83@yahoo.com.br"],
            ["name" => "Franz Schmidt", "email" => "franzschmidt@gmail.com"],
            ["name" => "Ramon Finelli Avendanha Marinho", "email" => "ramonfam@hotmail.com"],
            ["name" => "Bruno Francisco Ferreira", "email" => "brunofec@yahoo.com.br"],
            ["name" => "Marcus Vinicios Meneses de Matos", "email" => "contato@pedipag.com.br"],
            ["name" => "Felipe Augusto Ribeiro Matos", "email" => "felipearmatos@hotmail.com"],
            ["name" => "Thiago Castro Pelegrini", "email" => "thiagopeleg@gmail.com"],
            ["name" => "Rodrigo Jubert A. Moreira", "email" => "rodrigojubert@hotmail.com"],
            ["name" => "Gustavo Lele Frizzone", "email" => "frizone@gmail.com"],
            ["name" => "Breno Lages Lima", "email" => "brenolages@gmail.com"],
            ["name" => "Rodrigo Gavioli de Assis", "email" => "gavioli.ef@gmail.com"],
            ["name" => "Guilherme Figueiredo dos Santos Reis", "email" => "guilhermef91@hotmail.com"],
            ["name" => "Felipe de Oliveira Pereira", "email" => "felipe.op13@hotmail.com"],
            ["name" => "Frederico Augusto Andrade e Oliveira", "email" => "fredaaoliveira@gmail.com"],
            ["name" => "Claus Veronesi Boerger", "email" => "clausgames2309@gmail.com"],
            ["name" => "Gustavo Fagundes Garcia", "email" => "gutfgarcia@gmail.com"],
            ["name" => "Guilherme Ricardo Costa", "email" => "GUILHERMERCOZ@HOTMAIL.COM"],
            ["name" => "Rodrigo Bavaresco Brigatto", "email" => "rodrigobrigatto@gmail.com"],
            ["name" => "Victor Prates Timo", "email" => "victorprates.geo@gmail.com"],
            ["name" => "Thales Eduardo Barboza", "email" => "thalisideal@gmail.com"],
            ["name" => "André Matheus Rodrigues", "email" => "andre_matheus12@outlook.com"],
            ["name" => "Filipe Gustavo Lopes", "email" => "filipeglopes@hotmail.com"],
            ["name" => "Wellington Fadul Belgues", "email" => "wellingtonfadul@yahoo.com.br"],
            ["name" => "Wellington Pereira", "email" => "well230782@gmail.com"],
            ["name" => "André de Abreu Andrade", "email" => "andredeabreu83@gmail.com"],
            ["name" => "Carlos Augusto Vidotti Castro Correa", "email" => "carlosvidotticastrocorrea@gmail.com"],
            ["name" => "Túlio Parreira Camargos Guimarães", "email" => "tulio.camargos@gmail.com"],
            ["name" => "Yuri Philipe Motta dos Santos", "email" => "yuripmotta@gmail.com"],
            ["name" => "João Márcio Brandão Maciel", "email" => "jmacieltech@gmail.com"],
            ["name" => "Bruno Santana de Freitas", "email" => "bfreitas87@gmail.com"],
            ["name" => "Paulo Vinicius Resende Correa", "email" => "Paulovzp@gmail.com"],
            ["name" => "Rafael Junio Oliveira dos Passos", "email" => "caeloliveira1@hotmail.com"],
            ["name" => "Filipe Guimaraes Fernandes", "email" => "filipeguima@yahoo.com.br"],
            ["name" => "Paulo Mauricio de Paula Cysne", "email" => "paulomauriciocysne@gmail.com"],
            ["name" => "Thiago Coelho Toscano", "email" => "thiago.toscano@gmail.com"],
            ["name" => "Rafael Jack de Almeida Orlandi", "email" => "rafael_orlandi@yahoo.com.br"],
            ["name" => "Fábio Vieira Rodrigues", "email" => "fabioxeon@gmail.com"],
            ["name" => "Ronaldo César Lima Campos", "email" => "ronaldocesarcampos@hotmail.com"],
            ["name" => "Andres Felipe Cuadros Mateus", "email" => "pipemateus@gmail.com"],
            ["name" => "Cirano Navarro de Almeida Passos", "email" => "Cirano.passos@hotmail.com"],
            ["name" => "Bruno Eduardo Alves de Souza", "email" => "bruno@endolifemed.com.br"],
            ["name" => "Arthur Antonio do Santos e Santos", "email" => "endobraxarthur@gmail.com"],
            ["name" => "Fabrício de Paiva Oliveira", "email" => "fabriciopaiva0@gmail.com"],
            ["name" => "Eduardo Pedrosa Siqueira", "email" => "dudu_siqueira@hotmail.com"],
            ["name" => "Luiz Henrique de Paula Resende", "email" => "luizhenrique@ludrix.com.br"],
            ["name" => "Luiz Eduardo Benhame Sales", "email" => "luizeduardo.edificacao@gmail.com"],
            ["name" => "Lucas Matos Muniz", "email" => "lucasmatosmuniz@gmail.com"],
            ["name" => "Guilherme Lúcio Queiroz Jardim", "email" => "guilhermelucio@gmail.com"],
            ["name" => "Waider Hebert Martins", "email" => "waider182@gmail.com"],
            ["name" => "Victor Lopes Nasser", "email" => "victor@tresauto.com.br"],
            ["name" => "Henrique Frossard Assis Pinheiro", "email" => "henpinheiro@hotmail.com"],
            ["name" => "Leonardo De Marco Fonseca", "email" => "leodemarco84@gmail.com"],
            ["name" => "Cláudio Antônio Borges Brunswick Alvares", "email" => "claudioborges73@yahoo.com"],
            ["name" => "Raphael Bernardes Fagundes", "email" => "raphaelfagundes@gmail.com"],
            ["name" => "Thiago Bissoli Gomes", "email" => "tbissoli@hotmail.com"],
            ["name" => "Claudio Sayão Dias", "email" => "claudiosayao@gmail.com"],
            ["name" => "Thiago De Carvalho Timochenco", "email" => "thiagotimo@yahoo.com.br"],
            ["name" => "Leonardo Morais Silva", "email" => "leomorais.br@gmail.com"],
            ["name" => "Uedson Pereira da Silva", "email" => "uedson.silva@stellantis.com"],
            ["name" => "Peterson Rodrigues Pedrosa", "email" => "petersonpedrosa@gmail.com"],
        ];

        $uniqueUsers = array_unique($users, SORT_REGULAR);

        foreach ($uniqueUsers as $user) {
            DB::table('users')->insert([
                'name' => $user['name'],
                'email' => $user['email'],
                'password' => Hash::make('bek@buritis2025'),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}

